/* DIALOG RESOURCE HEADER FILE */

/*[PDE:pick]*/
  
extern DLGITEM pickItems[];
extern DIALOG pick;

#define PICK1 0
#define PICK2 1
#define PICK3 2

/*[PDE:DlgSave]*/
 
extern DLGITEM DlgSaveItems[];
extern DIALOG DlgSave;

#define DLGFILE 0
#define DLGSAVE2 1

/*[PDE:edidlg]*/

extern DLGITEM edidlgItems[];
extern DIALOG edidlg;

#define EDI1 0
#define EDI2 1
#define EDI3 2
#define EDIDLG4 3

/*[PDE:stidlg]*/
 
extern DLGITEM stidlgItems[];
extern DIALOG stidlg;

#define STI1 0
#define STI2 1
#define STIDLG3 2

/*[PDE:btidlg]*/

extern DLGITEM btidlgItems[];
extern DIALOG btidlg;

#define BTI1 0
#define BTIDLG2 1

/*[PDE:chidlg]*/

extern DLGITEM chidlgItems[];
extern DIALOG chidlg;

#define CHI1 0
#define CHI2 1
#define CHIDLG3 2

/*[PDE:cmidlg]*/
 
extern DLGITEM cmidlgItems[];
extern DIALOG cmidlg;

#define CMI1 0
#define CMI2 1
#define CMI3 2
#define CMI4 3
#define CMIDLG5 4
#define CMIDLG6 5

/*[PDE:bmidlg]*/
 
extern DLGITEM bmidlgItems[];
extern DIALOG bmidlg;

#define BMI1 0
#define BMIDLG 1

/*[PDE:DlgSetup]*/

extern DLGITEM DlgSetupItems[];
extern DIALOG DlgSetup;

#define DLGFNAME 0
#define DLGNAME 1
#define DLGHANDLER 2
#define DLGFLAGS 3
#define DLGSETUP5 4

/*[PDE:Itmset]*/

extern DLGITEM ItmsetItems[];
extern DIALOG Itmset;

#define ITMNAME 0
#define ITMLABEL 1
#define ITMTYPE 2
#define ITMFLAGS 3
#define ITMSET5 4

/*[PDE:gridlg]*/
 
extern DLGITEM gridlgItems[];
extern DIALOG gridlg;

#define GRI1 0
#define GRI2 1
#define GRI3 2

/*[PDE:raidlg]*/

extern DLGITEM raidlgItems[];
extern DIALOG raidlg;

#define RAI1 0
#define RAI2 1
#define RAI3 2

/*[PDE:otheritem]*/

extern DLGITEM otheritemItems[];
extern DIALOG otheritem;

#define OTHERITEM1 0
#define OTHERITEM2 1

/*[PDE:lbidlg]*/

extern DLGITEM lbidlgItems[];
extern DIALOG lbidlg;

#define LBI1 0
#define LBI2 1

