/* DIALOG RESOURCE HEADER FILE */

/*[PDE:SFont]*/

extern DLGITEM SFontItems[];
extern DIALOG SFont;

#define FNAME 0
#define FONTID 1
#define HFNTYPE 2
#define VFNTYPE 3
#define FCLTYPE 4
#define SAVEFONT3 5
#define SFONT7 6

/*[PDE:OpenFont]*/

extern DLGITEM OpenFontItems[];
extern DIALOG OpenFont;

#define OPNAME 0
#define OPENFONT2 1

/*[PDE:FontSize]*/

extern DLGITEM FontSizeItems[];
extern DIALOG FontSize;

#define FONTW 0
#define FONTH 1
#define FONTSIZE3 2
#define FONTSIZE4 3
#define FONTSIZE5 4

